name: calorie_tracker
description: A calorie tracking app to monitor your daily intake

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^3.12.0
  firebase_auth: ^5.5.0
  cloud_firestore: ^5.6.4
  firebase_storage: ^12.4.3
  google_sign_in: ^6.1.4

  # State management
  provider: ^6.0.5

  # UI
  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0

  # Utils
  http: ^1.1.0
  http_parser: ^4.0.2
  intl: ^0.20.2
  image_picker: ^1.0.2
  path: ^1.8.3
  uuid: ^4.5.1
  shared_preferences: ^2.2.0
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/icons/
    - assets/images/

  # Fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
