// File generated by FlutterFire CLI.
// This file should be generated by running flutterfire configure, but we're creating a placeholder manually.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'Web platform is not yet configured. Update firebase_options.dart with web configuration.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCidcc6-EoqPlfWCwMYI3tv3qclgY1Vsbs',
    appId: '1:188202579094:android:88219941db17a5364a7eb7',
    messagingSenderId: '188202579094',
    projectId: 'caloriescounter-432de',
    storageBucket: 'caloriescounter-432de.firebasestorage.app',
  );

  // Replace these with your actual Firebase configuration values

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwO9BGIJVZZhI9cxWpY_ACIsYf4VAtrLM',
    appId: '1:188202579094:ios:3cb3e58782a570e14a7eb7',
    messagingSenderId: '188202579094',
    projectId: 'caloriescounter-432de',
    storageBucket: 'caloriescounter-432de.firebasestorage.app',
    iosClientId: '188202579094-jre4m5d16bnb0i1ukr1sq6kij2bamnp3.apps.googleusercontent.com',
    iosBundleId: 'com.example.calorieTracker',
  );

  // Replace these with your actual Firebase configuration values

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwO9BGIJVZZhI9cxWpY_ACIsYf4VAtrLM',
    appId: '1:188202579094:ios:3cb3e58782a570e14a7eb7',
    messagingSenderId: '188202579094',
    projectId: 'caloriescounter-432de',
    storageBucket: 'caloriescounter-432de.firebasestorage.app',
    iosClientId: '188202579094-jre4m5d16bnb0i1ukr1sq6kij2bamnp3.apps.googleusercontent.com',
    iosBundleId: 'com.example.calorieTracker',
  );

  // Replace these with your actual Firebase configuration values from GoogleService-Info.plist for macOS
}